"""Content pools. Big on purpose: rooms deal from these without repeats (see base.Deck), so a group
can play for a long time before anything comes round again.

House rules for prompts: kind and silly. Nothing about bodies, money troubles, identity, exes or
anything that could make someone feel singled out. Everyone should be happy to be ranked #1.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------------------------------
# Frenemy Radar: "who is most likely to..." (ranked, so every prompt must be fun to "win")
# ---------------------------------------------------------------------------------------------------
FRENEMY_PROMPTS: list[str] = [
    "Most likely to survive a zombie apocalypse",
    "Most likely to become a millionaire by accident",
    "Most likely to cry at a dog food advert",
    "First to text back 'on my way' while still in bed",
    "Would win a staring contest against a cat",
    "Most likely to adopt 14 houseplants and name them all",
    "Best at talking their way out of anything",
    "Would sleep through their own surprise party",
    "Most likely to be a secret superhero",
    "Always has snacks in their bag",
    "Most likely to go viral for the wrong reason",
    "Gives the worst directions with the most confidence",
    "Would survive a week on a desert island by sheer stubbornness",
    "Most likely to reply-all by mistake",
    "Runs on 'five more minutes' energy",
    "Most likely to win a hot-dog eating contest",
    "Most likely to befriend a pigeon",
    "Would be the first to volunteer for a magic trick",
    "Most likely to start a band in a garage",
    "Most likely to know every word of a musical",
    "Would bring a board game to a beach party",
    "Most likely to have a signature dance move",
    "Most likely to win a pub quiz single-handed",
    "Would build a fort out of sofa cushions as an adult",
    "Most likely to get a standing ovation for a toast",
    "Most likely to accidentally start a new trend",
    "Would make friends with the bouncer",
    "Most likely to have a fun fact for every occasion",
    "Would host the best dinner party",
    "Most likely to be the hero of a heist film",
    "Most likely to name their car",
    "Would win a karaoke battle",
    "Most likely to bake something for no reason",
    "Most likely to plan a trip down to the minute",
    "Most likely to be spontaneous and book a trip tonight",
    "Would take the best road-trip playlist",
    "Most likely to cheer loudest at a kids' football match",
    "Most likely to talk to plants",
    "Would be the best at a murder-mystery party",
    "Most likely to win a game show",
    "Most likely to remember everyone's birthday",
    "Would make the best tour guide",
    "Most likely to have a secret talent nobody knows about",
    "Most likely to be found in a bookshop at closing time",
    "Would be the calmest in a crisis",
    "Most likely to become a famous chef",
    "Most likely to laugh at their own joke before the punchline",
    "Would ace a spelling bee",
    "Most likely to keep a houseplant alive for 20 years",
    "Most likely to win a sandcastle competition",
    "Would be the best astronaut",
    "Most likely to have the most organised sock drawer",
    "Most likely to make a new friend in a queue",
    "Would make the best detective",
    "Most likely to write a bestselling novel",
    "Most likely to get recognised by a celebrity",
    "Would be the best at charades",
    "Most likely to win an award for a pun",
    "Most likely to turn up with a cake",
    "Would be the first to jump in the sea",
    "Most likely to collect something unusual",
    "Most likely to be voted class president",
    "Would make the best wedding speech",
    "Most likely to learn a language just for fun",
    "Most likely to have a perfect impression of someone famous",
    "Would survive longest on a reality show",
    "Most likely to run a marathon on a whim",
    "Most likely to own matching outfits with their pet",
    "Would be the best getaway driver (in a video game)",
    "Most likely to have the best handwriting",
    "Most likely to win a dance-off",
    "Would make the best teacher",
    "Most likely to grow the biggest pumpkin",
    "Most likely to cheer everyone up on a bad day",
    "Would be the first to try a weird new food",
    "Most likely to get lost in a museum and love it",
    "Most likely to make a spreadsheet for fun",
    "Would be the best at hide and seek",
    "Most likely to have a famous catchphrase",
    "Most likely to win a cooking show",
    "Would make the best radio DJ",
    "Most likely to save the day with a paperclip",
    "Most likely to have read the instructions",
    "Would be the best at escape rooms",
    "Most likely to start a book club",
    "Most likely to become a YouTube sensation",
    "Would win a paper-aeroplane contest",
    "Most likely to make up a song on the spot",
    "Most likely to be a time traveller in disguise",
    "Would be the best at keeping a party going",
    "Most likely to win a chess tournament",
    "Most likely to have a garden that wins prizes",
    "Would ride a rollercoaster ten times in a row",
    "Most likely to get the whole room singing",
    "Most likely to rescue a lost animal",
    "Would make the best game-show host",
    "Most likely to win at mini-golf",
    "Most likely to know a shortcut everywhere",
    "Would be the best at a quiz about films",
    "Most likely to become a lighthouse keeper",
    "Most likely to win a costume contest",
    "Would make the best sidekick",
    "Most likely to have the perfect gift idea",
    "Most likely to win a pie-eating contest",
    "Would be chosen to lead the expedition",
    "Most likely to open a cosy café",
    "Most likely to make a friend on holiday and keep them for life",
    "Would be the best at building flat-pack furniture",
    "Most likely to win a trivia night about the 90s",
    "Most likely to be invited on a talk show",
    "Would invent something brilliant by accident",
    "Most likely to win a tug of war",
    "Most likely to do a cartwheel at a wedding",
    "Would be the best at keeping a straight face",
    "Most likely to have a theme song",
    "Most likely to find the best seat in a restaurant",
    "Would win a marshmallow-stacking contest",
    "Most likely to become a park ranger",
    "Most likely to convince everyone to go on an adventure",
    "Would be the best at telling ghost stories",
    "Most likely to win a bake-off",
    "Most likely to learn magic tricks",
    "Would make the best coach",
    "Most likely to win a talent show",
    "Most likely to make everyone a friendship bracelet",
    "Would be the best travel buddy",
    "Most likely to write a poem for a birthday card",
    "Most likely to be found humming",
    "Would be the best at a treasure hunt",
    "Most likely to start a conga line",
    "Most likely to keep a diary for 30 years",
    "Would make the best mayor",
    "Most likely to win a photo competition",
    "Most likely to go on a quest for the perfect sandwich",
    "Would be the best at guessing the end of a film",
    "Most likely to make the best pancakes",
    "Most likely to win an argument with a sat-nav",
    "Would be the first to the dance floor",
    "Most likely to become a famous inventor",
    "Most likely to have a lucky charm",
    "Would make the best pirate captain",
    "Most likely to know the name of every star",
    "Most likely to win at bingo",
    "Would be the best at assembling a jigsaw",
    "Most likely to cheer for the underdog",
    "Most likely to win a gold medal in napping",
    "Would be the wise old wizard in a fantasy film",
    "Most likely to win a pumpkin-carving contest",
    "Most likely to be the life of a road trip",
    "Would make the best robot inventor",
    "Most likely to have the best Halloween costume",
    "Most likely to win a dodgeball game",
    "Would be the best at giving pep talks",
    "Most likely to become a famous painter",
    "Most likely to run a lemonade stand as an adult",
    "Would be the best at a snowball fight",
    "Most likely to win a game of Monopoly",
    "Most likely to tell the best bedtime stories",
    "Would make the best space-station commander",
    "Most likely to be the one everyone calls for advice",
    "Most likely to win a hula-hoop contest",
    "Would be the best at naming pets",
    "Most likely to turn a rainy day into an adventure",
]

# ---------------------------------------------------------------------------------------------------
# Price Is Weird: absurd things with a price. Kept plausible-ish so guessing is a skill.
# ---------------------------------------------------------------------------------------------------


def _item(name: str, blurb: str, emoji: str, price: int) -> dict[str, Any]:
    return {"name": name, "blurb": blurb, "emoji": emoji, "price": price}


PRICE_ITEMS: list[dict[str, Any]] = [
    _item("Used lighthouse", "Minor haunting. Sold as-is. Lamp not included.", "🗼", 450_000),
    _item("Sentient toaster", "Judges your bread choices. Has opinions about rye.", "🍞", 2_400),
    _item("Pre-owned submarine", "One careful owner. Smells faintly of soup.", "🚢", 1_200_000),
    _item("Haunted vending machine", "Dispenses regret and sometimes crisps.", "🥤", 6_000),
    _item("Suit of armour, medium", "Squeaks when it thinks no one is listening.", "🛡️", 14_000),
    _item("Vintage typewriter, cursed", "Only types the word 'soon'.", "⌨️", 3_800),
    _item("Small cloud", "Hand-harvested. Rains on request. Mostly.", "☁️", 900),
    _item("Gently used time machine", "Only goes forward. At the normal speed.", "⏳", 88_000),
    _item("Medieval castle (draughty)", "Moat is more of a puddle these days.", "🏰", 2_600_000),
    _item("Talking parrot, rude", "Fluent in three languages and all the wrong words.", "🦜", 1_500),
    _item("Rocking chair, self-rocking", "Never fully stops. Please do not make eye contact.", "🪑", 1_100),
    _item("Mini monorail", "Seats four. Goes in one loop. Very proud of it.", "🚝", 320_000),
    _item("Crystal ball, slightly cracked", "Predictions arrive a bit late.", "🔮", 700),
    _item("Lifetime supply of left socks", "Right socks sold separately. And never.", "🧦", 240),
    _item("Hot-air balloon with opinions", "Refuses to fly on Mondays.", "🎈", 52_000),
    _item("Antique robot butler", "Polite, thorough, quietly keeping notes.", "🤖", 19_000),
    _item("Private island, tiny", "One palm tree. Very exclusive. Very windy.", "🏝️", 740_000),
    _item("Dragon egg (probably)", "Warm to the touch. Do not leave near curtains.", "🥚", 36_000),
    _item("Grand piano, bit damp", "Plays itself at 3 a.m. Always the same song.", "🎹", 9_500),
    _item(
        "Wizard's tower, fixer-upper",
        "Stairs rearrange themselves. Planning permission pending.",
        "🧙",
        380_000,
    ),
    _item("Gold-plated stapler", "Staples nothing. Looks incredible doing it.", "📎", 1_250),
    _item("Retired racing snail", "Won three races. Moved slowly to retirement.", "🐌", 86),
    _item("Bespoke umbrella for a goose", "Waterproof. Goose not included.", "☂️", 160),
    _item("Life-size chocolate moose", "Not a typo. Antlers are praline.", "🫎", 4_300),
    _item("Self-driving shopping trolley", "Has a slight left pull and big dreams.", "🛒", 2_900),
    _item("Treehouse with a lift", "Three floors. One very tired squirrel concierge.", "🌳", 68_000),
    _item("Professional bubble wrap", "Pre-popped for your convenience.", "🫧", 46),
    _item("Ice sculpture of a fridge", "Keeps itself cold. Briefly.", "🧊", 1_800),
    _item("Vintage arcade cabinet", "High score held by someone called 'MUM'.", "🕹️", 3_400),
    _item("Llama for a day", "Arrives with sunglasses. Leaves with your sandwich.", "🦙", 350),
    _item("Underwater hotel room", "Fish knock. Do not answer.", "🐠", 12_000),
    _item("Kettle that whistles show tunes", "Mostly the one from that musical.", "🫖", 130),
    _item("Medieval jousting lesson", "Horse is very patient. Lance is foam.", "🐎", 420),
    _item(
        "Fully working trebuchet", "Flings watermelons 200 metres. Neighbours sold separately.", "🏹", 24_000
    ),
    _item("Toy train set, enormous", "Fills a ballroom. Needs a timetable.", "🚂", 46_000),
    _item("Penguin-themed wedding cake", "Seven tiers. Every guest gets a fish.", "🐧", 2_100),
    _item("Vintage double-decker bus", "Converted into a library. Fines are in buttons.", "🚌", 58_000),
    _item("Ghost-hunting starter kit", "Includes torch, notebook and a very brave hat.", "👻", 190),
    _item("Ballpit for grown-ups", "10,000 balls. One is lost forever.", "🔴", 5_200),
    _item("Signed photo of a famous horse", "The horse used a hoof. It counts.", "🐴", 640),
    _item("Pocket-sized volcano", "Erupts with lemonade. Educational, sticky.", "🌋", 76),
    _item("Bouncy castle shaped like a real castle", "Turrets, flags, small bouncy moat.", "🏯", 7_800),
    _item("Bespoke family crest", "Featuring a badger holding a teacup.", "🛡️", 950),
    _item("Telescope that only sees the moon", "Very good at it, though.", "🔭", 1_400),
    _item("One acre of the moon (certificate)", "Legally fuzzy. Emotionally binding.", "🌕", 46),
    _item("Penny-farthing bicycle", "Comes with a very high seat and a ladder.", "🚲", 3_100),
    _item("Antique diving helmet", "Brass, heavy, extremely dramatic.", "🤿", 6_700),
    _item("Hand-knitted jumper for a tortoise", "Fits shell sizes S to L.", "🐢", 38),
    _item("Soundproof karaoke booth", "Your neighbours will thank us.", "🎤", 16_000),
    _item("Garden gnome army (50)", "Each one has a name and a grudge.", "🧑‍🌾", 1_200),
    _item("Life-size cardboard astronaut", "Great at parties. Terrible at conversation.", "👩‍🚀", 90),
    _item("Hovercraft, gently used", "Floats over lawns. And small dogs, politely.", "🛥️", 28_000),
    _item("Waterslide into a pool of jelly", "Strawberry. Absolutely not food-safe.", "🍓", 11_500),
    _item("Clock that runs backwards", "Technically correct twice a day.", "🕰️", 260),
    _item("Fountain that dispenses lemonade", "Bees: extremely interested.", "⛲", 9_900),
    _item("Professional sandcastle builder (day)", "Turrets guaranteed. Tide not.", "🏖️", 800),
    _item("Hand-painted portrait of your cat", "In the style of a Renaissance duke.", "🖼️", 520),
    _item("Antique carousel horse", "Goes up and down. Mostly down now.", "🎠", 8_200),
    _item("Treasure chest (empty)", "Very convincing. Arrr.", "🧰", 340),
    _item("Pet rock with a passport", "Has seen more of the world than most.", "🪨", 26),
    _item("Mechanical elephant ride", "Trunk sprays confetti on request.", "🐘", 190_000),
    _item("Tiny house on wheels", "Everything folds. Including you.", "🏠", 72_000),
    _item("Vintage phone box", "Now a shower. Please close the door.", "☎️", 4_900),
    _item("Movie-prop lightsaber", "Hums. Does not cut. Please stop asking.", "⚔️", 2_200),
    _item("Ferris wheel for the garden", "Eight seats. Planning officer seat optional.", "🎡", 410_000),
    _item("Magic carpet (unflown)", "Hovers about 2 mm. A start.", "🧞", 3_300),
    _item("Hedge maze, one acre", "Includes a minotaur-shaped topiary.", "🌿", 95_000),
    _item("Life jacket for a goldfish", "Unclear why. Sold out twice.", "🐟", 18),
    _item("Fortune-cookie printing press", "All fortunes say 'you will buy a printing press'.", "🥠", 6_100),
    _item("Spaceship-shaped bed", "Countdown alarm clock built in.", "🚀", 2_700),
    _item(
        "Taxidermy-free dinosaur skeleton (resin)", "Full-size T. rex. Ceiling height matters.", "🦖", 120_000
    ),
    _item("Monogrammed rubber duck", "Duck has a better signature than you.", "🦆", 12),
    _item("Vintage jukebox", "Plays one song. Very well.", "📻", 7_400),
    _item("Bespoke tuxedo for a dog", "Tails, obviously.", "🐕", 450),
    _item("Glass-bottomed boat", "Fish look up. Awkward.", "⛵", 33_000),
    _item("Secret bookcase door", "Pull the right book. Wrong book: just a book.", "📚", 5_600),
    _item("Popcorn machine, cinema-sized", "Makes 200 portions an hour. You'll need friends.", "🍿", 3_900),
    _item("Vintage hearse (now a taco truck)", "Respectfully delicious.", "🌮", 41_000),
    _item("Gingerbread house, walk-in", "Load-bearing icing. Do not lean.", "🍪", 13_000),
    _item("Mood ring for a horse", "Mostly shows 'hungry'.", "💍", 60),
    _item("Twelve-foot inflatable flamingo", "For pools, or emotional support.", "🦩", 420),
    _item("Antique globe with a country that no longer exists", "Ask it about the old days.", "🌍", 2_350),
    _item("Hand-carved chess set (life-size)", "Knights are actual rocking horses.", "♟️", 17_500),
    _item("Sleeper train cabin for one night", "Pyjamas strongly encouraged.", "🛏️", 380),
    _item("Coin-operated fortune teller", "Predicts you'll put in another coin.", "🔮", 9_200),
    _item("Indoor snow machine", "Covers a living room in 20 minutes. Regret in 21.", "❄️", 2_050),
    _item("Pirate ship climbing frame", "Plank not included, for insurance reasons.", "🏴‍☠️", 26_000),
    _item("Antique microscope", "Shows you things you can't unsee.", "🔬", 1_650),
    _item("Pair of rollerblades for a cat", "Cat has declined. Firmly.", "🐈", 56),
    _item("Signed rubber chicken", "Signed by a professional clown, of course.", "🐔", 30),
    _item("Bespoke crown", "Fake gems, real attitude.", "👑", 1_900),
    _item("Fully stocked sweet shop (one day)", "You can eat the stock. You will regret it.", "🍬", 7_000),
    _item("Mini zip line for the garden", "40 metres. Squirrels use it now.", "🪂", 4_400),
    _item("Vintage scooter with sidecar", "Sidecar has its own cup holder.", "🛵", 12_800),
    _item("Hand-blown glass pickle", "A Christmas tradition nobody can explain.", "🥒", 22),
    _item("Ventriloquist's dummy, retired", "Still thinks it's the main act.", "🎭", 1_350),
    _item("Golden toilet", "Fully plumbed. Fully ridiculous.", "🚽", 1_100_000),
    _item("Private concert by a kazoo orchestra", "Forty kazoos. One conductor. No mercy.", "🎶", 2_600),
    _item("Ancient sword (replica of a replica)", "Every chip is historically inaccurate.", "🗡️", 680),
    _item("Hammock big enough for six", "Group naps only. It's the law.", "🏕️", 870),
    _item("Bonsai tree, 300 years old", "Has outlived four owners. Watching you.", "🌲", 96_000),
    _item("Glow-in-the-dark wallpaper", "Bedroom becomes a galaxy. Sleep optional.", "✨", 310),
    _item("Pizza oven shaped like a dragon", "Breathes fire out of its nose. On purpose.", "🍕", 4_750),
    _item("Theatre curtain, red velvet", "For dramatic entrances to the kitchen.", "🎪", 3_600),
    _item("Self-stirring soup pot", "Stirs. Also hums. Also judges.", "🍲", 140),
    _item("Vintage cinema projector", "Comes with one film: a 1958 documentary on cheese.", "📽️", 5_100),
    _item("Bunk beds shaped like a castle", "Two towers, one slide, no peace.", "🏰", 3_200),
    _item("Portable igloo", "Assembles in 10 minutes. Melts in 11.", "🛖", 990),
    _item("Air-guitar trophy (official)", "Won by someone. Now yours.", "🏆", 76),
    _item("Electric go-kart for grown-ups", "Top speed: suspiciously fast.", "🏎️", 8_800),
    _item("Lifetime library card for a fictional town", "Overdue fines in imaginary money.", "🪪", 16),
    _item("Hand-built canal boat", "Moves at 4 mph. Lifestyle choice.", "🛶", 115_000),
    _item("Smoke machine for dramatic entrances", "For parties. And Mondays.", "💨", 210),
    _item("Antique diving bell", "Three people, one bell, many questions.", "🔔", 49_000),
    _item("A whole train carriage", "Retired. Wheels sold separately.", "🚃", 62_000),
    _item("Owl-shaped doorbell", "Hoots. Nobody can tell it's the door.", "🦉", 48),
    _item("Hand-stitched superhero cape", "Will not make you fly. We checked.", "🦸", 230),
    _item("Pool table that's also a dining table", "Snooker loopy dinner parties.", "🎱", 6_300),
    _item("Pocket watch from a sunken ship", "Stopped at teatime, forever.", "⌚", 4_200),
    _item("Vintage fire engine", "Bell works. Hose works. Neighbours: alert.", "🚒", 85_000),
    _item("Custom neon sign", "Says anything you want. Choose wisely.", "💡", 640),
    _item("Treasure map (blank)", "X marks wherever you like.", "🗺️", 20),
    _item("Life-size gingerbread person", "Run, run, as fast as you can.", "🍪", 160),
    _item("Indoor treehouse for cats", "Five levels. Cats will sit in the box it came in.", "🐱", 1_450),
    _item("Bespoke perfume that smells like rain", "Also faintly of library.", "🌧️", 280),
    _item("Escape-room in a box", "You're locked in your own house. Good luck.", "🔐", 120),
    _item("Antique sundial", "Works beautifully, weather permitting.", "☀️", 1_150),
    _item("Hand-carved wooden spaceship", "Doesn't fly. Smells like pine.", "🛸", 3_050),
    _item("Pet snail racing track", "Twelve lanes. One race takes all afternoon.", "🏁", 340),
    _item("Fully restored jukebox diner booth", "Milkshakes not included, sadly.", "🍔", 5_900),
    _item("Unicycle with a cup holder", "Ambitious.", "🥤", 176),
    _item("Two tickets to the moon (waitlist)", "Position 48,212. Estimated: later.", "🌙", 250_000),
    _item("Private ice rink for an evening", "Zamboni ride included.", "⛸️", 3_500),
    _item("Giant inflatable rubber duck", "Six metres tall. Floats majestically.", "🦆", 9_000),
    _item("Mechanical bull, retired", "Now mostly a slow, thoughtful sway.", "🐂", 4_100),
    _item("Original wind-up music box", "Plays a lullaby only grandmothers know.", "🎼", 780),
    _item("Hand-forged horseshoe (lucky)", "Luck not guaranteed. Horseshoe is.", "🧲", 40),
    _item("Bespoke hot sauce named after you", "Mild. Like your personality? No, spicy!", "🌶️", 96),
    _item("Fully working steam locomotive", "Coal, whistle, the works.", "🚂", 1_850_000),
    _item("Lighthouse lens (giant)", "Very bright. Do not look into it, Gary.", "🔦", 210_000),
    _item("Rooftop hot tub for one night", "City views. Rubber duck included.", "🛁", 650),
    _item("Clockwork owl", "Turns its head 270 degrees. Creepily well.", "🦉", 2_900),
    _item("Sword-swallowing lessons (beginner)", "Lesson one is mostly paperwork.", "🎪", 150),
    _item("Collection of 1,000 snow globes", "One of them has a tiny you in it.", "🔮", 3_700),
    _item("Ice-cream van, chimes included", "Plays 'Greensleeves' forever.", "🍦", 23_000),
    _item("Professional confetti cannon", "One shot. Weeks of cleaning.", "🎉", 330),
    _item("Velvet throne", "For sitting importantly.", "🪑", 2_450),
    _item("Antique carriage (no horse)", "Horse sold separately, as always.", "🛞", 31_000),
    _item("Mini golf course for the living room", "Nine holes. One under the sofa.", "⛳", 1_050),
    _item("A star named after you", "Unofficial. Still shines.", "⭐", 50),
    _item("Bespoke tree swing", "Oak seat, hand-plaited rope, pure joy.", "🌳", 410),
    _item("Professional magician's top hat", "Rabbit status: unknown.", "🎩", 380),
    _item("Ancient-looking scroll (new)", "Says 'Happy birthday' in fake Latin.", "📜", 36),
    _item("Fully furnished castle in Scotland", "Comes with a ghost and a sheep.", "🏴", 9_500_000),
    _item("A tonne of LEGO-like bricks", "Instructions not included. Pain included.", "🧱", 7_200),
    _item("Hot-sauce flight for one", "Six sauces. Bring milk.", "🔥", 28),
    _item("Bespoke kite shaped like a whale", "Twelve metres. Gentle giant of the skies.", "🐋", 590),
    _item("Pocket sundial", "Useful for about half the day.", "🧭", 66),
    _item("Antique rocking horse", "Glass eyes. Seen things.", "🐎", 1_700),
    _item("Pet tarantula hotel", "Five-star. Very small stars.", "🕷️", 140),
    _item("Fully stocked pirate costume chest", "Parrot is plush. Probably.", "🦜", 260),
    _item("Old red post box", "Letters still go in. Never come out.", "📮", 2_800),
    _item("Vintage camper van", "Curtains, kettle, freedom.", "🚐", 54_000),
    _item("Quill and inkpot set", "For writing dramatic letters about the bins.", "🪶", 70),
]

# ---------------------------------------------------------------------------------------------------
# Alibi: a murder in a new place every game. 6 locations, 6 half-hour slots, one victim.
# ---------------------------------------------------------------------------------------------------
ALIBI_SETTINGS: list[dict[str, Any]] = [
    {
        "title": "Murder at the Manor",
        "victim": "Lord Ashby",
        "locations": ["Kitchen", "Garden", "Library", "Cellar", "Balcony", "Garage"],
        "slots": ["7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM", "9:00 PM", "9:30 PM"],
    },
    {
        "title": "Death on the Riverboat",
        "victim": "Captain Marlowe",
        "locations": ["Bridge", "Galley", "Ballroom", "Engine room", "Sun deck", "Cabins"],
        "slots": ["9:00 PM", "9:30 PM", "10:00 PM", "10:30 PM", "11:00 PM", "11:30 PM"],
    },
    {
        "title": "Snowed In at the Ski Lodge",
        "victim": "Madame Frost",
        "locations": ["Lobby", "Sauna", "Ski shop", "Bar", "Ice rink", "Boot room"],
        "slots": ["6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM"],
    },
    {
        "title": "Crisis on Station Kepler",
        "victim": "Commander Vega",
        "locations": ["Command deck", "Hydroponics", "Airlock", "Med bay", "Observatory", "Reactor"],
        "slots": ["0600", "0630", "0700", "0730", "0800", "0830"],
    },
    {
        "title": "Curtains at the Circus",
        "victim": "The Great Bombastico",
        "locations": ["Big top", "Trailer park", "Menagerie", "Costume tent", "Ticket booth", "Trapeze rig"],
        "slots": ["5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM"],
    },
    {
        "title": "Cut! Murder on Set",
        "victim": "Director Dashwood",
        "locations": ["Sound stage", "Make-up", "Catering", "Prop store", "Editing suite", "Car park"],
        "slots": ["1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM"],
    },
    {
        "title": "The Museum Gala",
        "victim": "Curator Pemberton",
        "locations": ["Egyptian hall", "Gift shop", "Roof terrace", "Vault", "Dinosaur wing", "Cloakroom"],
        "slots": ["8:00 PM", "8:30 PM", "9:00 PM", "9:30 PM", "10:00 PM", "10:30 PM"],
    },
    {
        "title": "Vintage Vineyard Mystery",
        "victim": "Old Monsieur Brie",
        "locations": ["Wine cellar", "Vines", "Press house", "Terrace", "Tasting room", "Stables"],
        "slots": ["4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM"],
    },
    {
        "title": "The Lighthouse Island",
        "victim": "Keeper Gulliver",
        "locations": ["Lamp room", "Jetty", "Cottage", "Cliff path", "Boathouse", "Storm cellar"],
        "slots": ["10:00 PM", "10:30 PM", "11:00 PM", "11:30 PM", "Midnight", "12:30 AM"],
    },
    {
        "title": "Murder on the Midnight Express",
        "victim": "Baroness Velour",
        "locations": ["Dining car", "Sleeper car", "Luggage van", "Observation car", "Engine", "Bar car"],
        "slots": ["11:00 PM", "11:30 PM", "Midnight", "12:30 AM", "1:00 AM", "1:30 AM"],
    },
    {
        "title": "Checkout at the Grand Hotel",
        "victim": "Mr Featherstonehaugh",
        "locations": ["Reception", "Ballroom", "Laundry", "Penthouse", "Pool", "Kitchens"],
        "slots": ["7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM", "9:00 PM", "9:30 PM"],
    },
    {
        "title": "The Castle Banquet",
        "victim": "Duke Thistlewood",
        "locations": ["Great hall", "Armoury", "Chapel", "Dungeon", "Battlements", "Herb garden"],
        "slots": ["6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM"],
    },
]

# ---------------------------------------------------------------------------------------------------
# Telepathy Tax: a category and six options. Match some minds, not the whole room.
# ---------------------------------------------------------------------------------------------------
TELEPATHY_CATEGORIES: list[dict[str, Any]] = [
    {"title": c, "options": o}
    for c, o in [
        ("A breakfast food", ["Toast", "Pancakes", "Cereal", "Eggs", "Porridge", "Croissant"]),
        ("A colour", ["Red", "Blue", "Green", "Yellow", "Purple", "Orange"]),
        ("A farm animal", ["Cow", "Pig", "Sheep", "Chicken", "Horse", "Goat"]),
        ("A pizza topping", ["Pepperoni", "Mushroom", "Pineapple", "Olives", "Onion", "Extra cheese"]),
        ("A season", ["Spring", "Summer", "Autumn", "Winter", "Monsoon", "Holiday season"]),
        (
            "A superpower",
            ["Flying", "Invisibility", "Teleporting", "Super strength", "Mind reading", "Time travel"],
        ),
        ("Something at the beach", ["Sandcastle", "Seagull", "Ice cream", "Sunscreen", "Waves", "Crab"]),
        ("A board game", ["Chess", "Monopoly", "Scrabble", "Cluedo", "Snakes and ladders", "Draughts"]),
        ("A fruit", ["Apple", "Banana", "Strawberry", "Mango", "Grapes", "Watermelon"]),
        ("A musical instrument", ["Guitar", "Piano", "Drums", "Violin", "Trumpet", "Flute"]),
        ("A planet", ["Mars", "Jupiter", "Saturn", "Earth", "Venus", "Neptune"]),
        ("A sport", ["Football", "Tennis", "Basketball", "Swimming", "Cricket", "Golf"]),
        ("A dessert", ["Ice cream", "Cake", "Brownie", "Cheesecake", "Trifle", "Apple pie"]),
        ("Something in a kitchen", ["Kettle", "Fridge", "Toaster", "Spoon", "Oven", "Blender"]),
        ("A wild animal", ["Lion", "Elephant", "Giraffe", "Tiger", "Zebra", "Monkey"]),
        ("A kind of weather", ["Sunny", "Rain", "Snow", "Wind", "Fog", "Thunderstorm"]),
        ("A job", ["Teacher", "Doctor", "Chef", "Firefighter", "Pilot", "Artist"]),
        ("A shape", ["Circle", "Square", "Triangle", "Star", "Heart", "Hexagon"]),
        ("A vegetable", ["Carrot", "Broccoli", "Potato", "Peas", "Sweetcorn", "Onion"]),
        ("Something in space", ["Moon", "Star", "Rocket", "Comet", "Black hole", "Astronaut"]),
        ("A drink", ["Tea", "Coffee", "Orange juice", "Lemonade", "Hot chocolate", "Milkshake"]),
        ("A fairy-tale character", ["Cinderella", "Big bad wolf", "Dragon", "Witch", "Giant", "Frog prince"]),
        ("Something with wheels", ["Bike", "Car", "Bus", "Skateboard", "Train", "Shopping trolley"]),
        ("A room in a house", ["Kitchen", "Bedroom", "Bathroom", "Living room", "Attic", "Garden shed"]),
        ("A sandwich filling", ["Cheese", "Ham", "Tuna", "Egg", "Peanut butter", "Chicken"]),
        ("A sea creature", ["Shark", "Dolphin", "Octopus", "Whale", "Jellyfish", "Starfish"]),
        ("A holiday", ["Beach", "Mountains", "City break", "Theme park", "Countryside", "Cruise"]),
        ("Something in a pocket", ["Keys", "Phone", "Coins", "Receipt", "Tissue", "Sweets"]),
        ("A bird", ["Robin", "Owl", "Penguin", "Parrot", "Eagle", "Flamingo"]),
        ("A thing at a party", ["Balloons", "Cake", "Music", "Games", "Presents", "Snacks"]),
        ("A school subject", ["Maths", "English", "Science", "History", "Art", "PE"]),
        ("A tree", ["Oak", "Pine", "Palm", "Willow", "Birch", "Apple tree"]),
        ("A snack", ["Crisps", "Popcorn", "Chocolate", "Biscuits", "Nuts", "Fruit"]),
        ("A dance", ["Salsa", "Ballet", "Tango", "Hip hop", "Disco", "Conga"]),
        ("Something cold", ["Ice", "Snow", "Freezer", "Ice lolly", "Penguin", "Glacier"]),
        ("Something hot", ["Sun", "Fire", "Chilli", "Oven", "Volcano", "Cup of tea"]),
        ("A pet", ["Dog", "Cat", "Hamster", "Goldfish", "Rabbit", "Parrot"]),
        ("A pasta", ["Spaghetti", "Penne", "Lasagne", "Macaroni", "Ravioli", "Fusilli"]),
        ("A card game", ["Snap", "Poker", "Uno", "Solitaire", "Go fish", "Rummy"]),
        ("A fantasy creature", ["Dragon", "Unicorn", "Mermaid", "Phoenix", "Troll", "Fairy"]),
        ("Something in a bathroom", ["Toothbrush", "Towel", "Soap", "Mirror", "Rubber duck", "Shampoo"]),
        ("A cheese", ["Cheddar", "Brie", "Mozzarella", "Parmesan", "Feta", "Stilton"]),
        ("A thing you plug in", ["Phone charger", "Kettle", "TV", "Lamp", "Hair dryer", "Toaster"]),
        ("A flower", ["Rose", "Sunflower", "Daisy", "Tulip", "Lily", "Daffodil"]),
        ("Something with stripes", ["Zebra", "Tiger", "Bee", "Candy cane", "Flag", "Deckchair"]),
        ("Something in a classroom", ["Whiteboard", "Desk", "Pencil", "Globe", "Ruler", "Clock"]),
        ("A cartoon animal", ["Mouse", "Duck", "Rabbit", "Cat", "Bear", "Dog"]),
        ("A camping item", ["Tent", "Torch", "Sleeping bag", "Marshmallows", "Map", "Campfire"]),
        ("A hat", ["Baseball cap", "Top hat", "Beanie", "Cowboy hat", "Crown", "Sun hat"]),
        ("A nut", ["Peanut", "Almond", "Cashew", "Walnut", "Hazelnut", "Pistachio"]),
        ("Something round", ["Ball", "Pizza", "Coin", "Wheel", "Orange", "Clock"]),
        ("Something in the sky", ["Cloud", "Bird", "Plane", "Rainbow", "Kite", "Sun"]),
        ("A thing at the circus", ["Clown", "Juggler", "Trapeze", "Lion", "Big top", "Popcorn"]),
        ("A dog breed", ["Labrador", "Poodle", "Bulldog", "Dachshund", "Husky", "Corgi"]),
        ("A soup", ["Tomato", "Chicken noodle", "Minestrone", "Pea", "Mushroom", "Lentil"]),
        ("A bug", ["Ladybird", "Bee", "Butterfly", "Ant", "Spider", "Beetle"]),
        ("A thing in a toolbox", ["Hammer", "Screwdriver", "Spanner", "Tape measure", "Nails", "Saw"]),
        ("A cake flavour", ["Chocolate", "Vanilla", "Lemon", "Carrot", "Red velvet", "Coffee"]),
        ("A winter thing", ["Scarf", "Snowman", "Hot chocolate", "Gloves", "Sledge", "Fireplace"]),
        ("A summer thing", ["Ice cream", "Sunglasses", "Barbecue", "Paddling pool", "Fan", "Flip-flops"]),
        ("A breakfast drink", ["Tea", "Coffee", "Orange juice", "Milk", "Smoothie", "Water"]),
        ("A mythical place", ["Atlantis", "El Dorado", "Narnia", "Camelot", "Olympus", "Wonderland"]),
        ("A way to travel", ["Plane", "Train", "Boat", "Car", "Bicycle", "Hot-air balloon"]),
        ("Something sticky", ["Glue", "Honey", "Tape", "Jam", "Chewing gum", "Syrup"]),
        ("A thing that buzzes", ["Bee", "Phone", "Alarm clock", "Doorbell", "Fly", "Electric toothbrush"]),
        ("A sauce", ["Ketchup", "Mayonnaise", "Mustard", "Barbecue", "Soy sauce", "Gravy"]),
        ("A famous kind of building", ["Castle", "Pyramid", "Lighthouse", "Skyscraper", "Temple", "Palace"]),
        ("A bedtime thing", ["Pillow", "Teddy", "Pyjamas", "Story", "Night light", "Duvet"]),
        ("A fast animal", ["Cheetah", "Falcon", "Horse", "Hare", "Greyhound", "Ostrich"]),
        ("A slow thing", ["Snail", "Tortoise", "Sloth", "Traffic jam", "Queue", "Glacier"]),
        ("A shoe", ["Trainers", "Boots", "Sandals", "Slippers", "Wellies", "High heels"]),
        ("A smoothie fruit", ["Banana", "Strawberry", "Blueberry", "Mango", "Pineapple", "Kiwi"]),
        ("A spooky thing", ["Ghost", "Bat", "Skeleton", "Pumpkin", "Witch", "Spider"]),
        ("A thing in a park", ["Swing", "Bench", "Duck pond", "Slide", "Tree", "Ice-cream van"]),
        ("A sweet", ["Lollipop", "Gummy bear", "Toffee", "Chocolate bar", "Mint", "Marshmallow"]),
        ("A thing you wear in winter", ["Coat", "Scarf", "Gloves", "Woolly hat", "Boots", "Jumper"]),
        ("A mood", ["Happy", "Excited", "Sleepy", "Surprised", "Grumpy", "Calm"]),
        ("A big number", ["Hundred", "Thousand", "Million", "Billion", "Infinity", "Googol"]),
        ("Something yellow", ["Banana", "Sun", "Lemon", "Rubber duck", "Taxi", "Cheese"]),
        ("Something green", ["Grass", "Frog", "Leaf", "Broccoli", "Cactus", "Lime"]),
        ("Something red", ["Apple", "Fire engine", "Strawberry", "Rose", "Post box", "Ladybird"]),
        ("Something blue", ["Sky", "Sea", "Blueberry", "Jeans", "Whale", "Sapphire"]),
        ("A kitchen gadget", ["Whisk", "Toaster", "Microwave", "Kettle", "Grater", "Peeler"]),
        ("A pirate thing", ["Treasure", "Parrot", "Ship", "Eye patch", "Map", "Cutlass"]),
        ("A space job", ["Astronaut", "Alien", "Rocket pilot", "Scientist", "Engineer", "Robot"]),
        ("A funfair food", ["Candyfloss", "Hot dog", "Popcorn", "Toffee apple", "Doughnut", "Churros"]),
        ("A word for great", ["Awesome", "Brilliant", "Amazing", "Fantastic", "Excellent", "Superb"]),
        ("A thing at the zoo", ["Penguin", "Lion", "Gift shop", "Monkey", "Elephant", "Map"]),
        (
            "A detective tool",
            ["Magnifying glass", "Notebook", "Torch", "Fingerprint kit", "Camera", "Deerstalker hat"],
        ),
        ("A bakery item", ["Bread", "Croissant", "Doughnut", "Muffin", "Cookie", "Sausage roll"]),
        ("A thing people collect", ["Stamps", "Coins", "Shells", "Stickers", "Rocks", "Postcards"]),
        ("A garden thing", ["Gnome", "Flowers", "Hose", "Shed", "Lawnmower", "Bird feeder"]),
        ("A thing with buttons", ["Remote", "Shirt", "Lift", "Phone", "Calculator", "Coat"]),
        ("Half of a famous pair", ["Salt", "Pepper", "Fish", "Chips", "Bread", "Butter"]),
        ("A morning sound", ["Alarm", "Birds", "Kettle", "Shower", "Radio", "Traffic"]),
        ("A game-show prize", ["Car", "Holiday", "Cash", "Trophy", "Speedboat", "Fridge"]),
        ("A magic trick prop", ["Top hat", "Rabbit", "Wand", "Cards", "Coin", "Cape"]),
        ("A thing that flies", ["Bird", "Plane", "Kite", "Butterfly", "Bee", "Drone"]),
        ("A tool for drawing", ["Pencil", "Crayon", "Marker", "Paintbrush", "Chalk", "Pen"]),
        ("A thing in a forest", ["Mushroom", "Deer", "Owl", "Log", "Fox", "Stream"]),
        ("A thing in a museum", ["Dinosaur", "Mummy", "Painting", "Statue", "Gift shop", "Armour"]),
        ("A movie snack", ["Popcorn", "Nachos", "Sweets", "Hot dog", "Ice cream", "Fizzy drink"]),
    ]
]

# ---------------------------------------------------------------------------------------------------
# Mole in the Mural: tiles have a colour and a kind; hints must share one of them with the painting.
# ---------------------------------------------------------------------------------------------------
MURAL_TILES: list[dict[str, str]] = [
    {"emoji": e, "name": n, "color": c, "kind": k}
    for e, n, c, k in [
        ("🍎", "Apple", "red", "food"),
        ("🍓", "Strawberry", "red", "food"),
        ("🍒", "Cherries", "red", "food"),
        ("🌶️", "Chilli", "red", "food"),
        ("🍅", "Tomato", "red", "food"),
        ("🍉", "Watermelon", "green", "food"),
        ("🍋", "Lemon", "yellow", "food"),
        ("🍌", "Banana", "yellow", "food"),
        ("🧀", "Cheese", "yellow", "food"),
        ("🌽", "Corn", "yellow", "food"),
        ("🍊", "Orange", "orange", "food"),
        ("🥕", "Carrot", "orange", "food"),
        ("🎃", "Pumpkin", "orange", "food"),
        ("🥦", "Broccoli", "green", "food"),
        ("🥝", "Kiwi", "green", "food"),
        ("🍐", "Pear", "green", "food"),
        ("🥑", "Avocado", "green", "food"),
        ("🍇", "Grapes", "purple", "food"),
        ("🍆", "Aubergine", "purple", "food"),
        ("🫐", "Blueberries", "blue", "food"),
        ("🍫", "Chocolate", "brown", "food"),
        ("🍩", "Doughnut", "pink", "food"),
        ("🍞", "Bread", "brown", "food"),
        ("🥥", "Coconut", "brown", "food"),
        ("🍦", "Ice cream", "white", "food"),
        ("🥚", "Egg", "white", "food"),
        ("🍙", "Rice ball", "white", "food"),
        ("🦊", "Fox", "orange", "animal"),
        ("🐯", "Tiger", "orange", "animal"),
        ("🦁", "Lion", "yellow", "animal"),
        ("🐤", "Chick", "yellow", "animal"),
        ("🐝", "Bee", "yellow", "animal"),
        ("🐸", "Frog", "green", "animal"),
        ("🐢", "Turtle", "green", "animal"),
        ("🐊", "Crocodile", "green", "animal"),
        ("🦎", "Lizard", "green", "animal"),
        ("🐳", "Whale", "blue", "animal"),
        ("🐬", "Dolphin", "blue", "animal"),
        ("🐟", "Fish", "blue", "animal"),
        ("🦋", "Butterfly", "blue", "animal"),
        ("🐙", "Octopus", "purple", "animal"),
        ("🦄", "Unicorn", "purple", "animal"),
        ("🐷", "Pig", "pink", "animal"),
        ("🦩", "Flamingo", "pink", "animal"),
        ("🐻", "Bear", "brown", "animal"),
        ("🐴", "Horse", "brown", "animal"),
        ("🐿️", "Squirrel", "brown", "animal"),
        ("🐑", "Sheep", "white", "animal"),
        ("🐼", "Panda", "white", "animal"),
        ("🐧", "Penguin", "black", "animal"),
        ("🐈‍⬛", "Black cat", "black", "animal"),
        ("🦀", "Crab", "red", "animal"),
        ("🐞", "Ladybird", "red", "animal"),
        ("🦜", "Parrot", "red", "animal"),
        ("🌹", "Rose", "red", "nature"),
        ("🍁", "Maple leaf", "red", "nature"),
        ("🌻", "Sunflower", "yellow", "nature"),
        ("🌼", "Daisy", "yellow", "nature"),
        ("⭐", "Star", "yellow", "nature"),
        ("☀️", "Sun", "yellow", "nature"),
        ("🌵", "Cactus", "green", "nature"),
        ("🌲", "Pine tree", "green", "nature"),
        ("🍀", "Clover", "green", "nature"),
        ("🌊", "Wave", "blue", "nature"),
        ("💧", "Droplet", "blue", "nature"),
        ("❄️", "Snowflake", "white", "nature"),
        ("☁️", "Cloud", "white", "nature"),
        ("🌙", "Moon", "yellow", "nature"),
        ("🌸", "Blossom", "pink", "nature"),
        ("🌷", "Tulip", "pink", "nature"),
        ("🍄", "Mushroom", "red", "nature"),
        ("🔥", "Fire", "orange", "nature"),
        ("🌋", "Volcano", "orange", "nature"),
        ("🪨", "Rock", "black", "nature"),
        ("🌰", "Chestnut", "brown", "nature"),
        ("🪻", "Hyacinth", "purple", "nature"),
        ("🚗", "Car", "red", "transport"),
        ("🚒", "Fire engine", "red", "transport"),
        ("🚌", "Bus", "yellow", "transport"),
        ("🚕", "Taxi", "yellow", "transport"),
        ("🚜", "Tractor", "green", "transport"),
        ("🚙", "Jeep", "blue", "transport"),
        ("🚲", "Bike", "green", "transport"),
        ("🚀", "Rocket", "white", "transport"),
        ("✈️", "Plane", "white", "transport"),
        ("🚂", "Steam train", "black", "transport"),
        ("🛸", "UFO", "purple", "transport"),
        ("⛵", "Sailboat", "white", "transport"),
        ("🛶", "Canoe", "brown", "transport"),
        ("🚁", "Helicopter", "blue", "transport"),
        ("⚽", "Football", "white", "sport"),
        ("🏀", "Basketball", "orange", "sport"),
        ("🎾", "Tennis ball", "yellow", "sport"),
        ("🏈", "Rugby ball", "brown", "sport"),
        ("🥊", "Boxing glove", "red", "sport"),
        ("⛳", "Golf flag", "green", "sport"),
        ("🏓", "Ping pong", "red", "sport"),
        ("🎳", "Bowling", "white", "sport"),
        ("🛹", "Skateboard", "brown", "sport"),
        ("🥏", "Frisbee", "blue", "sport"),
        ("🏒", "Hockey stick", "brown", "sport"),
        ("🎱", "Pool ball", "black", "sport"),
        ("🎈", "Balloon", "red", "object"),
        ("❤️", "Heart", "red", "object"),
        ("📕", "Red book", "red", "object"),
        ("🔔", "Bell", "yellow", "object"),
        ("🔑", "Key", "yellow", "object"),
        ("👑", "Crown", "yellow", "object"),
        ("🧩", "Puzzle piece", "green", "object"),
        ("📗", "Green book", "green", "object"),
        ("💎", "Gem", "blue", "object"),
        ("🧢", "Cap", "blue", "object"),
        ("👖", "Jeans", "blue", "object"),
        ("☂️", "Umbrella", "purple", "object"),
        ("🔮", "Crystal ball", "purple", "object"),
        ("🎀", "Bow", "pink", "object"),
        ("👛", "Purse", "pink", "object"),
        ("🎻", "Violin", "brown", "object"),
        ("📦", "Box", "brown", "object"),
        ("🧸", "Teddy", "brown", "object"),
        ("🎩", "Top hat", "black", "object"),
        ("🕶️", "Sunglasses", "black", "object"),
        ("🦴", "Bone", "white", "object"),
        ("🧻", "Loo roll", "white", "object"),
        ("🎲", "Dice", "white", "object"),
        ("🏮", "Lantern", "red", "object"),
        ("🪁", "Kite", "pink", "object"),
    ]
]

# ---------------------------------------------------------------------------------------------------
# Crossword: answers (A-Z, 3-10 letters) and friendly clues. Grids are built fresh each game.
# ---------------------------------------------------------------------------------------------------
CROSSWORD_ENTRIES: list[dict[str, str]] = [
    {"word": w, "clue": c}
    for w, c in [
        ("APPLE", "Fruit that keeps the doctor away"),
        ("BANANA", "Yellow fruit monkeys love"),
        ("ORANGE", "Citrus fruit, or a colour"),
        ("LEMON", "Sour yellow citrus"),
        ("GRAPE", "Small fruit that becomes a raisin"),
        ("MANGO", "Tropical stone fruit"),
        ("PEACH", "Fuzzy-skinned summer fruit"),
        ("CHERRY", "Small red fruit on a cake"),
        ("PEAR", "Fruit shaped like a light bulb"),
        ("PLUM", "Purple fruit that dries into a prune"),
        ("MELON", "Big fruit with a rind"),
        ("KIWI", "Fuzzy green fruit, or a bird"),
        ("BREAD", "Loaf you slice for toast"),
        ("CHEESE", "Cheddar or brie"),
        ("BUTTER", "Spread made from cream"),
        ("PASTA", "Spaghetti or penne"),
        ("PIZZA", "Round dish with toppings"),
        ("SOUP", "Hot dish eaten with a spoon"),
        ("SALAD", "Bowl of leaves and veg"),
        ("TOAST", "Bread browned by heat"),
        ("HONEY", "Sweet stuff made by bees"),
        ("SUGAR", "Sweetener in your tea"),
        ("PEPPER", "Salt's partner"),
        ("ONION", "Vegetable that makes you cry"),
        ("CARROT", "Orange root a rabbit loves"),
        ("POTATO", "Spud"),
        ("TOMATO", "Red fruit in ketchup"),
        ("PEAS", "Little green balls from a pod"),
        ("BEAN", "Baked on toast, maybe"),
        ("RICE", "Grain served with curry"),
        ("CAKE", "Birthday treat with candles"),
        ("COOKIE", "Biscuit, across the pond"),
        ("JELLY", "Wobbly dessert"),
        ("CANDY", "Sweets"),
        ("WAFFLE", "Grid-patterned breakfast"),
        ("MUFFIN", "Cupcake's plainer cousin"),
        ("BAGEL", "Bread roll with a hole"),
        ("NOODLE", "Long thin strand of pasta"),
        ("SALT", "Seasoning from the sea"),
        ("TEA", "Hot drink made from leaves"),
        ("COFFEE", "Morning pick-me-up brewed from beans"),
        ("MILK", "White drink from cows"),
        ("JUICE", "Squeezed fruit drink"),
        ("WATER", "H2O"),
        ("CAT", "Pet that purrs"),
        ("DOG", "Pet that wags its tail"),
        ("HORSE", "Animal with a mane you can ride"),
        ("COW", "Farm animal that moos"),
        ("PIG", "Farm animal that oinks"),
        ("SHEEP", "Woolly farm animal"),
        ("GOAT", "Animal with a beard and horns"),
        ("DUCK", "Bird that quacks"),
        ("GOOSE", "Honking bird"),
        ("OWL", "Night bird that hoots"),
        ("EAGLE", "Large bird of prey"),
        ("PARROT", "Bird that can talk"),
        ("PENGUIN", "Bird that can't fly but swims"),
        ("LION", "King of the jungle"),
        ("TIGER", "Big striped cat"),
        ("ZEBRA", "Striped horse-like animal"),
        ("GIRAFFE", "Tallest animal"),
        ("MONKEY", "Banana-loving primate"),
        ("BEAR", "Big furry animal that hibernates"),
        ("PANDA", "Black and white bamboo eater"),
        ("KOALA", "Australian tree-hugger"),
        ("FOX", "Sly orange animal"),
        ("WOLF", "Animal that howls at the moon"),
        ("RABBIT", "Animal with long ears that hops"),
        ("MOUSE", "Small squeaky animal"),
        ("FROG", "Green hopper that croaks"),
        ("SNAKE", "Legless reptile that hisses"),
        ("TURTLE", "Reptile with a shell"),
        ("WHALE", "Largest animal in the sea"),
        ("SHARK", "Fish with a famous fin"),
        ("DOLPHIN", "Clever sea mammal that clicks"),
        ("OCTOPUS", "Sea creature with eight arms"),
        ("CRAB", "Sideways-walking shellfish"),
        ("BEE", "Insect that makes honey"),
        ("ANT", "Tiny insect that lives in a colony"),
        ("SPIDER", "Eight-legged web spinner"),
        ("SNAIL", "Slow creature with a shell"),
        ("CAMEL", "Desert animal with humps"),
        ("HIPPO", "River horse"),
        ("RHINO", "Animal with a horn on its nose"),
        ("SLOTH", "Very slow tree dweller"),
        ("BAT", "Flying mammal, or cricket gear"),
        ("SUN", "Star at the centre of our solar system"),
        ("MOON", "It orbits the Earth"),
        ("STAR", "Twinkle twinkle little ..."),
        ("PLANET", "Mars or Venus"),
        ("COMET", "Icy space visitor with a tail"),
        ("ROCKET", "It blasts off into space"),
        ("CLOUD", "Fluffy thing in the sky"),
        ("RAIN", "Water falling from clouds"),
        ("SNOW", "White winter flakes"),
        ("STORM", "Thunder and lightning"),
        ("WIND", "Moving air"),
        ("RAINBOW", "Arc of colours after rain"),
        ("RIVER", "Flowing body of water"),
        ("OCEAN", "Atlantic or Pacific"),
        ("ISLAND", "Land surrounded by water"),
        ("MOUNTAIN", "Very tall hill"),
        ("VOLCANO", "Mountain that erupts"),
        ("DESERT", "Dry sandy place"),
        ("FOREST", "Lots of trees"),
        ("BEACH", "Sandy place by the sea"),
        ("CAVE", "Hollow in a rock"),
        ("LAKE", "Large body of still water"),
        ("TREE", "Oak or pine"),
        ("FLOWER", "Rose or daisy"),
        ("GRASS", "Green stuff on a lawn"),
        ("LEAF", "It falls in autumn"),
        ("ROSE", "Red flower with thorns"),
        ("DAISY", "White flower with a yellow centre"),
        ("TULIP", "Spring flower from Holland"),
        ("CACTUS", "Spiky desert plant"),
        ("SEED", "It grows into a plant"),
        ("CAR", "Vehicle with four wheels"),
        ("BUS", "Big vehicle for many passengers"),
        ("TRAIN", "It runs on rails"),
        ("PLANE", "It flies you on holiday"),
        ("BOAT", "It floats on water"),
        ("SHIP", "Large ocean vessel"),
        ("BIKE", "Two wheels and pedals"),
        ("TAXI", "Car you hail"),
        ("TRUCK", "Lorry"),
        ("SCOOTER", "Two-wheeler you push along"),
        ("CASTLE", "Fortress with towers"),
        ("HOUSE", "Home"),
        ("SCHOOL", "Place for lessons"),
        ("BRIDGE", "It crosses a river"),
        ("TOWER", "Tall narrow building"),
        ("GARDEN", "Place to grow flowers"),
        ("KITCHEN", "Room where you cook"),
        ("BEDROOM", "Room where you sleep"),
        ("DOOR", "You knock on it"),
        ("WINDOW", "Glass pane in a wall"),
        ("ROOF", "Top of a house"),
        ("STAIRS", "Steps between floors"),
        ("CHAIR", "Seat with a back"),
        ("TABLE", "Furniture you eat at"),
        ("BED", "Furniture for sleeping"),
        ("SOFA", "Comfy seat for several"),
        ("LAMP", "It lights a room"),
        ("CLOCK", "It tells the time"),
        ("MIRROR", "It shows your reflection"),
        ("PILLOW", "Soft thing for your head"),
        ("BLANKET", "It keeps you warm in bed"),
        ("TOWEL", "Used to dry yourself"),
        ("SOAP", "Bar for washing hands"),
        ("BRUSH", "Tool for hair or paint"),
        ("COMB", "Toothed tool for hair"),
        ("PHONE", "You call people with it"),
        ("LAPTOP", "Portable computer"),
        ("CAMERA", "It takes photos"),
        ("RADIO", "It plays stations"),
        ("PIANO", "Instrument with black and white keys"),
        ("GUITAR", "Six-stringed instrument"),
        ("DRUM", "Instrument you hit"),
        ("VIOLIN", "Instrument played with a bow"),
        ("FLUTE", "Woodwind instrument you blow across"),
        ("TRUMPET", "Brass instrument"),
        ("SONG", "Music with words"),
        ("DANCE", "Move to music"),
        ("PARTY", "Celebration with friends"),
        ("GAME", "Something you play"),
        ("PUZZLE", "Jigsaw or crossword"),
        ("BALL", "Round thing you kick or throw"),
        ("KITE", "It flies on a string"),
        ("DOLL", "Toy figure"),
        ("TEDDY", "Cuddly bear"),
        ("ROBOT", "Mechanical helper"),
        ("DRAGON", "Fire-breathing beast"),
        ("UNICORN", "Horse with one horn"),
        ("WIZARD", "Magic user with a wand"),
        ("PIRATE", "Sailor who hunts treasure"),
        ("KNIGHT", "Soldier in armour"),
        ("PRINCESS", "King's daughter"),
        ("CROWN", "Royal headwear"),
        ("TREASURE", "Pirate's buried gold"),
        ("MAP", "It shows the way"),
        ("COMPASS", "It points north"),
        ("ANCHOR", "It keeps a ship in place"),
        ("TENT", "Camping shelter"),
        ("TORCH", "Light you carry"),
        ("CANDLE", "Wax light"),
        ("FIRE", "Flames"),
        ("ICE", "Frozen water"),
        ("STONE", "Small rock"),
        ("GOLD", "Precious yellow metal"),
        ("SILVER", "Second-place metal"),
        ("DIAMOND", "Hardest gem"),
        ("PEARL", "Gem from an oyster"),
        ("RING", "Jewellery for a finger"),
        ("HAT", "It goes on your head"),
        ("SCARF", "Wrap for your neck"),
        ("GLOVES", "They keep your hands warm"),
        ("BOOTS", "Tall shoes"),
        ("SOCKS", "They go in shoes"),
        ("SHIRT", "Top with buttons"),
        ("JACKET", "Short coat"),
        ("DRESS", "One-piece outfit"),
        ("SKIRT", "It hangs from the waist"),
        ("JEANS", "Denim trousers"),
        ("POCKET", "Pouch sewn into clothes"),
        ("BUTTON", "It fastens a shirt"),
        ("ZIP", "Fastener on a jacket"),
        ("BAG", "You carry things in it"),
        ("BOX", "Cardboard container"),
        ("BOTTLE", "Container with a neck"),
        ("CUP", "You drink from it"),
        ("PLATE", "You eat off it"),
        ("FORK", "Pronged eating tool"),
        ("SPOON", "Tool for soup"),
        ("KNIFE", "Cutting tool"),
        ("BOWL", "Dish for cereal"),
        ("KETTLE", "It boils water"),
        ("OVEN", "Where you bake"),
        ("FRIDGE", "It keeps food cold"),
        ("BOOK", "Pages bound together"),
        ("PENCIL", "Writing tool with lead"),
        ("PAPER", "Sheet you write on"),
        ("RULER", "It measures lines"),
        ("CHALK", "It writes on a blackboard"),
        ("TEACHER", "Person who gives lessons"),
        ("DOCTOR", "Person who treats the sick"),
        ("NURSE", "Hospital helper"),
        ("CHEF", "Professional cook"),
        ("PILOT", "Person who flies a plane"),
        ("FARMER", "Person who grows crops"),
        ("ARTIST", "Person who paints"),
        ("BAKER", "Person who makes bread"),
        ("CLOWN", "Circus funny person"),
        ("SINGER", "Person who sings"),
        ("ACTOR", "Person in a play"),
        ("KING", "Ruler with a crown"),
        ("QUEEN", "King's wife or chess piece"),
        ("FRIEND", "Buddy"),
        ("FAMILY", "Parents and children"),
        ("BABY", "Newborn"),
        ("HAPPY", "Feeling glad"),
        ("SLEEPY", "Feeling tired"),
        ("FUNNY", "It makes you laugh"),
        ("BRAVE", "Not scared"),
        ("QUIET", "Not loud"),
        ("FAST", "Quick"),
        ("SLOW", "Not fast"),
        ("TALL", "Not short"),
        ("WARM", "Not quite hot"),
        ("COLD", "Chilly"),
        ("RED", "Colour of a fire engine"),
        ("BLUE", "Colour of the sky"),
        ("GREEN", "Colour of grass"),
        ("YELLOW", "Colour of a banana"),
        ("PURPLE", "Colour of grapes"),
        ("PINK", "Colour of a flamingo"),
        ("BLACK", "Colour of night"),
        ("WHITE", "Colour of snow"),
        ("SPRING", "Season when flowers bloom"),
        ("SUMMER", "Hottest season"),
        ("AUTUMN", "Season of falling leaves"),
        ("WINTER", "Coldest season"),
        ("MONDAY", "First day of the working week"),
        ("FRIDAY", "Last day of the working week"),
        ("MORNING", "Start of the day"),
        ("NIGHT", "When it is dark"),
        ("BIRTHDAY", "Day for cake and candles"),
        ("HOLIDAY", "Time off for fun"),
        ("TENNIS", "Sport with rackets and a net"),
        ("SOCCER", "Football, in America"),
        ("GOLF", "Sport with holes and clubs"),
        ("CHESS", "Board game with kings and queens"),
        ("CARDS", "Deck of 52"),
        ("DICE", "Cubes you roll"),
        ("SWIM", "Move through water"),
        ("RUN", "Move faster than walking"),
        ("JUMP", "Leap into the air"),
        ("SING", "Make music with your voice"),
        ("LAUGH", "Ha ha!"),
        ("SMILE", "Happy face"),
        ("DREAM", "It happens while you sleep"),
        ("MAGIC", "Abracadabra!"),
        ("SECRET", "Something you keep to yourself"),
        ("PUPPY", "Young dog"),
        ("KITTEN", "Young cat"),
        ("LAMB", "Young sheep"),
        ("CALF", "Young cow"),
        ("ACORN", "Seed of an oak"),
        ("PUMPKIN", "Orange Halloween squash"),
        ("SNOWMAN", "Frosty figure with a carrot nose"),
        ("IGLOO", "House made of snow"),
        ("SLED", "It slides down snowy hills"),
        ("BALLOON", "Party decoration you blow up"),
        ("PRESENT", "Gift"),
        ("CIRCUS", "Show with clowns and acrobats"),
        ("MUSEUM", "Place to see old treasures"),
        ("LIBRARY", "Place to borrow books"),
        ("CINEMA", "Place to watch films"),
        ("AIRPORT", "Place where planes take off"),
        ("MARKET", "Place with stalls"),
        ("PARK", "Green space with swings"),
        ("ZOO", "Place to see wild animals"),
        ("FARM", "Place with barns and tractors"),
    ]
]
